const indianNames = [
  "Aarav",
  "Vivaan",
  "Aditya",
  "Vihaan",
  "Arjun",
  "Sai",
  "Krishna",
  "Ishaan",
  "Anaya",
  "Myra",
  "Diya",
  "Aadhya",
  "Kiara",
  "Saanvi",
  "Ira",
  "Tejas",
  "Riya",
  "Aanya",
  "Kartik",
  "Lakshya",
  "Rohan",
  "Neha",
  "Siddharth",
  "Priya",
  "Tanvi",
  "Yash",
  "Pooja",
  "Varun",
  "Sneha",
  "Rahul",
  "Shruti",
];

const hindiEnglishMessages = [
  "नमस्ते! कैसे हो?",
  "Good morning!",
  "आज मौसम बहुत अच्छा है।",
  "Let's catch up soon!",
  "क्या आप व्यस्त हैं?",
  "I'm working right now.",
  "मुझे फिल्में देखना पसंद है।",
  "What's your plan for today?",
  "चलो मिलते हैं!",
  "थोड़ा व्यस्त हूँ।",
  "I love Indian food!",
  "अभी पढ़ाई कर रहा हूँ।",
  "See you later!",
  "बिलकुल सही कहा।",
  "How's everything going?",
  "काफी अच्छा दिन है।",
  "I'm feeling great today!",
  "आपसे बात करके अच्छा लगा।",
  "Take care!",
  "ध्यान रखना!",
  "चलो चाय पीते हैं!",
  "Weekend के क्या plans हैं?",
  "आज बहुत traffic था।",
  "आज movie देखने चलें?",
  "Lunch किया?",
  "Busy day, थोड़ा थक गया हूँ।",
  "Exam की तैयारी कैसी चल रही है?",
  "काम से फुर्सत मिली?",
  "Thoda late हो जाऊंगा।",
  "Let's meet at 5 PM!",
  "Congrats on your achievement!",
  "All the best!",
  "जल्दी मिलते हैं।",
  "Have a safe journey!",
  "कल बहुत मजा आया।",
  "Miss you yaar!",
  "Party कब दे रहे हो?",
  "Thanks for your help!",
  "No problem, anytime!",
  "क्या तुम free हो आज?",
  "Feeling lazy today 😴",
  "बहुत गर्मी हो रही है।",
  "Rainy season शुरू हो गया।",
  "Office से निकल रहा हूँ।",
  "चलो बाहर घूमते हैं।",
  "I am craving pani puri!",
  "बहुत बोर हो रहा हूँ।",
  "Life is beautiful!",
  "नया phone लिया क्या?",
  "Bhai, gym कब चलना है?",
  "Sundays are for relaxing.",
  "Let's go shopping!",
  "Homework finished?",
  "India जीत गई! 🎉",
  "Cricket match देखा?",
  "Family के साथ time बिता रहा हूँ।",
];

const getRandomItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

export const generateRandomNames = () => {
  return getRandomItem(indianNames);
};

export const generateRandomMessages = () => {
  return getRandomItem(hindiEnglishMessages);
};
